[project]
name = "portswigger-labs-with-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=5.4.0",
    "pyperclip>=1.9.0",
    "requests>=2.32.3",
]
